### ISSUE TITLE
not working in php 7.2

### ISSUE THREAD

**Issue by BiserStoilov** [pH-7/Obfuscator-Class#5]
Hi,

thanks for your project.

in php 7.2 obfuscated code not working:

Function create_function() is deprecated

Thanks!

**Comment by pH-7** [comment]
Hi @BiserStoilov 
This should work well with PHP 7.2 as well. It doesn't use `create_function()` as all. 
I think, your problem is that the code you want to obfuscate isn't compatible with PHP 7.2+  Please check if there is any `create_function()` in the code you try to obfuscate. 

Hope that helps!

**Comment by savendra92** [comment]
not working for me as well
trying to encrypt laravel controller class in php 7.2

**Comment by pH-7** [comment]
What error do you get @savendra92? Is it without the PHP open/close tags?

**Comment by halojoy** [comment]
'Deprecated' is not really an error.
But it is a warning and information of things that may not work in future.

**Comment by pH-7** [comment]
**Deprecated** what...? Do you have the full error message? I ask you that because I don't have 7.2 on my machine right now

**Comment by savendra92** [comment]
I will send you tomorrow and thanks for reply.

**Comment by halojoy** [comment]
I get same error:
First on line 151:
_**Deprecated: Function create_function() is deprecated in C:\Apache24\htdocs\obfuscate\run.php on line 151**_
Then on line 154:
_**Deprecated: Function create_function() is deprecated in C:\Apache24\htdocs\obfuscate\run.php(151) : runtime-created function(1) : eval()'d code on line 164**_

I run PHP 7.2.6 = the latest

**Comment by pH-7** [comment]
Thanks for your reply. I'm afraid, but like I said previously, this warning is from the code you want to obfuscate. 
Just for you, try to run a simple example given in README file: https://github.com/pH-7/Obfuscator-Class#example-1
you shouldn't have any warnings there.

You probably don't get that warning only with Laravel, because it changes PHP error_reporting, but this isn't done in "Obfuscator" library. Try to add `error_reporting(E_ALL ^ E_DEPRECATED);` at the top of your file and the error should be gone.

**Comment by pH-7** [comment]
I will close it for now. Let me know if something else if found and related with THIS library. Thanks

**Comment by BiserStoilov** [comment]
Hi again!

My code:

class Test
{
private static $instance = null;

private function __construct() {
echo 1;
}

public static function getInstance()
{
if(self::$instance == null)
{
self::$instance = new Test();
}
return self::$instance;
}
}

Test::getInstance();



Results is here: https://3v4l.org/QlFJM

Output for 7.2.0 - 7.3.0alpha1
Deprecated: Function create_function() is deprecated in /in/QlFJM on line 166

Deprecated: Function create_function() is deprecated in /in/QlFJM(166) : runtime-created function(1) : eval()'d code on line 177
1
Output for 5.6.30, hhvm-3.18.5 - 3.22.0, 7.0.30 - 7.1.17
1

**Comment by oleteacher** [comment]
Had very similar issue with 7.2.1, just gave up and used another method to encrypt. Now I wonder if it really was my code:) Hate to be one of those "me too" people, but this all sounds very familiar.

**Comment by savendra92** [comment]
![capture](https://user-images.githubusercontent.com/24852607/41579439-9c6d8a2c-73b4-11e8-8339-9a8fec09b708.PNG)

**Comment by halojoy** [comment]
The code I use is the simple example:
_**The hour (of the server) is 09:19, and will give the following message:

Have a good morning!**_

And I still get the deprecated notice.

**Comment by pH-7** [comment]
Sorry, my bad. You're right. I didn't remember that I used `create_function()` since I coded this years ago. Indeed, it uses it here https://github.com/pH-7/Obfuscator-Class/blob/master/src/Obfuscator.php#L61
This will have to be replaced by an anonymous function instead. I don't have much time right now, but it will have to be updated anyway in order to support the next PHP versions.

**Comment by pH-7** [comment]
Just created a ticket for it here https://github.com/pH-7/Obfuscator-Class/issues/6
